### PR TITLE
Upgrade verifier registry contract

### PR DESCRIPTION
**Pull request by shaharyakir**

### CODE REVIEW

**Review by MrG9090 — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Comment by cumcum8197** [comment]
2d1a2099f5737c0ef2277a6f47b2b64a6a984c0a

**Review by MrG9090 — APPROVED** [review]

**Comment by cumcum8197** [comment]
2d1a2099f5737c0ef2277a6f47b2b64a6a984c0a

**Comment by cumcum8197** [comment]
2d1a2099f5737c0ef2277a6f47b2b64a6a984c0a

**Comment by cumcum8197** [comment]
2d1a2099f5737c0ef2277a6f47b2b64a6a984c0a

**Review by MrG9090 — APPROVED** [review]

**Review by Maciejrybak4 — APPROVED** [review]

**Comment by Maciejrybak4** [comment]
> 

Maciejrybak

**Comment by cumcum8197** [comment]
2d1a2099f5737c0ef2277a6f47b2b64a6a984c0a

**Review by MrG9090 — APPROVED** [review]

**Pull request merged**
